-- FOLLOW-UP PLAN (no-op template): after core.hospitals merge + column backfill,
-- chart_pdf / health_report style schemas should reference canonical hospital ids.
--
-- Attach DB was `public.*`. Target layout on 우리 DB:
--
--   chart_pdf           documents  (DDL: supabase/migrations/20260503230300_chart_pdf_documents.sql)
--   chart_pdf           parse_runs  (DDL: supabase/migrations/20260503230400_chart_pdf_parse_runs.sql)
--   chart_pdf           report_case_images   (DDL: supabase/migrations/20260503230500_chart_pdf_report_case_images.sql; staging: create-staging-report-case-images.sql / 일괄 스크립트)
--   chart_pdf           result_basic_info    (DDL: supabase/migrations/20260503230600_chart_pdf_result_basic_info.sql)
--   chart_pdf           result_chart_by_date (DDL: supabase/migrations/20260503230700_chart_pdf_result_chart_by_date.sql)
--   chart_pdf           result_lab_items     (〃)
--   chart_pdf           result_physical_exam_items (〃)
--   chart_pdf           result_plan_rows     (〃)
--   chart_pdf           result_vaccination_records (〃)
--   chart_pdf           result_vitals        (〃)
--
--   health_report       generated_run_content  (DDL: supabase/migrations/20260503230000_health_report_generated_run_content.sql)
--   health_report       health_review_share_links  (DDL: 20260503230100… + stub upgrade 20260503230200…)
--
-- Not listed here: public.hospitals → already canonical via core.hospitals + hospital_pdf_merge_map.
-- Schemas created by migration 20260503220000_chart_pdf_health_report_schemas.sql.
--
-- Intended sequence:
--   1) Ensure every application hospital_id value resolves via hospital_pdf_merge_map
--      (or equivalent) to core.hospitals.id (text).
--   2) Backfill child tables: UPDATE ... SET hospital_id = mapped_core_id WHERE ...;
--   3) Alter column types if needed (uuid → text) only after values match core.hospitals.id text form.
--   4) ADD CONSTRAINT ... FOREIGN KEY (hospital_id) REFERENCES core.hospitals (id)
--      ON UPDATE CASCADE ON DELETE RESTRICT (or team-default semantics).
--   5) Drop obsolete merge staging tables / legacy FKs once replicas and apps agree.
--
-- Chart ingestion migrations live under supabase/migrations/ — add real DDL there when
-- those schemas land in this repo; keep this file as runbook notes only.

select 'followup-chart-pdf-health-report-hospital-fk-plan — documented steps only' as status;
