export const HEALTH_CHECKUP_MAX_OVERALL_CHARS = 600;
export const HEALTH_CHECKUP_MAX_FOLLOW_UP_CHARS = 600;
export const HEALTH_CHECKUP_MIN_OVERALL_CHARS = 500;
export const HEALTH_CHECKUP_MIN_FOLLOW_UP_CHARS = 500;

export const HEALTH_CHECKUP_MAX_RECHECK_TITLE_CHARS = 15;
export const HEALTH_CHECKUP_MAX_RECHECK_BODY_CHARS = 50;

export const HEALTH_CHECKUP_MAX_COVER_FIELD_CHARS = 500;
export const HEALTH_CHECKUP_MAX_COVER_SHORT_FIELD_CHARS = 7;
export const HEALTH_CHECKUP_MAX_COVER_CHECKUP_DATE_CHARS = 32;
export const HEALTH_CHECKUP_MAX_COVER_SEX_CHARS = 12;

export const HEALTH_CHECKUP_SYSTEMS_ROW_MAX_CHARS = 320;
export const HEALTH_CHECKUP_DENTAL_SKIN_ROW_MAX_CHARS = 250;
export const HEALTH_CHECKUP_LAB_INTERP_MAX_CHARS = 250;

export const HEALTH_CHECKUP_MUST_INCLUDE_MAX_CHARS = 1000;
